### ISSUE TITLE
Problem: Clicking on the mathjax bookmarlet gives a html page with the word 'TRUE'.

### ISSUE THREAD

**Issue by talegari** [dzejkej/mathjax-bookmarklet#11]
Problem: Clicking on the mathjax bookmarlet gives a html page with the word 'TRUE'.

**Comment by kubetz** [comment]
Cannot reproduce this behavior. More information would be appreciated.

Are you using the most recent version from http://kubetz.github.io/mathjax-bookmarklet/ ?
If you click on the bookmarklet there, do you get the HTML page? 
What browser (& version) are you using?
Do you have javascript enabled?

**Comment by kubetz** [comment]
Closing as there was no future feedback/information and I was not able to reproduce it myself.
