### ISSUE TITLE
not working on facebook

### ISSUE THREAD

**Issue by franciscovargas** [dzejkej/mathjax-bookmarklet#12]
anyway to get workaround to make it work on facebook?

**Comment by franciscovargas** [comment]
Refused to load the script 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_HTMLorMML.js' because it violates the following Content Security Policy directive: "script-src _.facebook.com *.fbcdn.net *.facebook.net *.google-analytics.com *.virtualearth.net *.google.com 127.0.0.1:_ _.spotilocal.com:_ 'unsafe-inline' 'unsafe-eval' *.akamaihd.net *.atlassolutions.com blob: chrome-extension://lifbcibllhkdhoafpjfnlhfpfgnpldfl".

**Comment by kubetz** [comment]
For security reasons they disabled injecting scripts from domains not specified in that list. I don't think there is a workaround and even if there was I don't think it would be a good thing trying to bypass their security policy.
