### ISSUE TITLE
Could U add support to math delimiters $$...$$ 

### ISSUE THREAD

**Issue by linhua55** [dzejkej/mathjax-bookmarklet#6]
For example:
https://plus.google.com/117158790449271841902/posts/CUcRnqSn3gM

**Comment by dzejkej** [comment]
$$ delims were added for inline math.

Please reinstall the bookmarklet here: http://dzejkej.github.io/mathjax-bookmarklet/

Let me know if it works.

PS: Your example link is not working. Google is telling me that the post was either deleted or I don't have privileges to see it.

**Comment by linhua55** [comment]
It works like a charm.Appreciate your work.
