### ISSUE TITLE
Third-party extension support

### ISSUE THREAD

**Issue by mindbound** [dzejkej/mathjax-bookmarklet#7]
Could it be possible to add [third-party MathJax extension](http://docs.mathjax.org/en/latest/options/ThirdParty.html) support? It would be great to use this to render e.g. XyJax diagrams.

Appending `try{MathJax.Ajax.config.path[\'Contrib\']=\'http://cdn.mathjax.org/mathjax/contrib\';}catch(e){1}` before `MathJax.Hub.Config({extensions:[\'[Contrib]/xyjax/xypic.js\'] ...` doesn't seem to work (xyjax.js is loaded but it doesn't render the graphics).

**Comment by dzejkej** [comment]
I had a look into XyJax documentation and it seems that you have to also activate the extension itself `MathJax.Hub.Config({...TeX: {extensions: ["xypic.js"]}...

Source: [here](https://github.com/sonoisa/XyJax).

Try making a bookmarklet from this:

    javascript:!function(){function a(a){var b=".MathJax .mn {background: inherit;} .MathJax .mi {color: inherit;} .MathJax .mo {background: inherit;}",c=a.createElement("style");c.innerText=b;try{c.textContent=b}catch(d){}a.getElementsByTagName("body")[0].appendChild(c);var f,e=a.createElement("script");e.src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_HTMLorMML.js",e.type="text/javascript",f="MathJax.Ajax.config.path['Contrib']='//cdn.mathjax.org/mathjax/contrib';MathJax.Hub.Config({extensions:['[Contrib]/xyjax/xypic.js'], tex2jax:{inlineMath:[['$','$'],['$$', '$$']],displayMath:[['\\\\[','\\\\]']],processEscapes:true},TeX:{extensions: ['ypic.js']}});MathJax.Hub.Startup.onload();",window.opera?e.innerHTML=f:e.text=f,a.getElementsByTagName("head")[0].appendChild(e)}function b(b){void 0===b.MathJax?a(b.document):b.MathJax.Hub.Queue(new b.Array("Typeset",b.MathJax.Hub))}var d,e,c=document.getElementsByTagName("iframe");for(b(window),d=0;d<c.length;d++)e=c[d].contentWindow||c[d].contentDocument,e.document||(e=e.parentNode),b(e)}();

Note: It is still necessary to have the Xy-pic code delimeted.

**Comment by kubetz** [comment]
I added he XyJax support into the bookmarklet and updated example page with the sample XyPic code.

Let me know if it works for you!

**Comment by mindbound** [comment]
It works. Many thanks for adding the functionality and for the quick response.
